# Generated by Django 5.2.5 on 2025-08-08 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticketpriority_ticketstatus_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketpriority',
            options={'verbose_name_plural': 'TicketPriorities'},
        ),
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'verbose_name_plural': 'TicketStatus'},
        ),
        migrations.CreateModel(
            name='UserMenuAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_level1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menulevel1')),
                ('menu_level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menulevel2')),
                ('menu_level3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menulevel3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'menu_level1', 'menu_level2', 'menu_level3')},
            },
        ),
    ]
