# Generated by Django 5.2.5 on 2025-08-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ticketpriority_name_alter_ticketstatus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='actions',
            field=models.ManyToManyField(related_name='permissions', to='core.action'),
        ),
    ]
