# Generated by Django 5.2.5 on 2025-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_action_permission_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='resouce',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('resouce', 'name')},
        ),
    ]
