# Generated by Django 5.2.5 on 2025-08-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_action_resouce_alter_action_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPermissionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.action')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
            ],
            options={
                'unique_together': {('action', 'permission')},
            },
        ),
    ]
