# Generated by Django 5.2.5 on 2025-08-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_actionpermissionmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='resouce',
            new_name='resource',
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('resource', 'name')},
        ),
        migrations.DeleteModel(
            name='ActionPermissionMap',
        ),
    ]
