# Generated by Django 5.2.5 on 2025-08-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpriority',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
